export const WORD_BANK = [
  "Coleoptera",
  "Lepidoptera",
  "Diptera",
  "Hymenoptera",
  "Orthoptera",
  "Odonata",
  "Hemiptera",
  "Neuroptera",
  "Blattodea",
  "Mantodea",
  "Phasmatodea",
  "Dermaptera",
  "Ephemeroptera",
  "Plecoptera",
  "Trichoptera",
  "Siphonaptera",
  "Mecoptera",
  "Thysanoptera",
  "Megaloptera",
  "Raphidioptera",
  "butterfly",
  "moth",
  "beetle",
  "fly",
  "bee",
  "wasp",
  "ant",
  "grasshopper",
  "cricket",
  "dragonfly",
  "damselfly",
  "firefly",
  "ladybird",
  "ladybug",
  "bumblebee",
  "honeybee",
  "monarch",
  "walkingstick",
  "mantis",
  "cockroach",
  "earwig",
  "mayfly",
  "stonefly",
  "caddisfly",
  "flea",
  "aphid",
  "cicada",
  "katydid",
  "locust",
  "silkworm",
  "glowworm",
  "weevil",
  "hornet",
  "yellowjacket",
  "sawfly",
  "leafhopper",
  "whitefly",
  "thrips",
  "silverfish",
  "bristletail",
  "dobsonfly",
  "snakefly",
  "lacewing",
  "antlion",
  "mealworm",
  "wireworm",
  "cutworm",
  "armyworm",
  "inchworm",
  "looper",
  "swallowtail",
  "skipper",
  "hairstreak",
  "fritillary",
  "admiral",
  "birdwing",
  "hawkmoth",
  "sphinx",
  "geometrid",
  "noctuid",
  "saturniid",
  "longhorn",
  "scarab",
  "dung beetle",
  "ground beetle",
  "tiger beetle",
  "diving beetle",
  "whirligig",
  "click beetle",
  "soldier beetle",
  "bark beetle",
  "rove beetle",
  "blister beetle",
  "antenna",
  "antennae",
  "thorax",
  "abdomen",
  "head",
  "compound eye",
  "ocellus",
  "ocelli",
  "proboscis",
  "tarsus",
  "tarsi",
  "femur",
  "tibia",
  "coxa",
  "trochanter",
  "spiracle",
  "tergite",
  "sternite",
  "cercus",
  "cerci",
  "ovipositor",
  "aedeagus",
  "clasper",
  "labrum",
  "labium",
  "mandible",
  "maxilla",
  "galea",
  "lacinia",
  "palp",
  "clypeus",
  "frons",
  "vertex",
  "gena",
  "occiput",
  "pronotum",
  "mesothorax",
  "metathorax",
  "prothorax",
  "pleuron",
  "elytron",
  "elytra",
  "haltere",
  "tegmen",
  "alula",
  "pterostigma",
  "seta",
  "setae",
  "chaeta",
  "sensillum",
  "tympanum",
  "stridulum",
  "rostrum",
  "arolium",
  "pulvillus",
  "empodium",
  "forewing",
  "hindwing",
  "costa",
  "subcosta",
  "radius",
  "cubitus",
  "jugum",
  "remigium",
  "membrane",
  "corium",
  "clavus",
  "cuneus",
  "petiole",
  "pedicel",
  "scape",
  "flagellum",
  "larva",
  "larvae",
  "pupa",
  "pupae",
  "imago",
  "imagines",
  "instar",
  "nymph",
  "naiad",
  "chrysalis",
  "cocoon",
  "exuvia",
  "exuviae",
  "eclosion",
  "ecdysis",
  "moulting",
  "metamorphosis",
  "holometabolism",
  "hemimetabolism",
  "ametabolism",
  "diapause",
  "aestivation",
  "univoltine",
  "bivoltine",
  "multivoltine",
  "brood",
  "clutch",
  "ootheca",
  "ovum",
  "ova",
  "spermatophore",
  "puparium",
  "prepupa",
  "teneral",
  "sclerotization",
  "tanning",
  "sclerotized",
  "hardening",
  "hatching",
  "pollination",
  "eusociality",
  "swarming",
  "migration",
  "aposematism",
  "mimicry",
  "camouflage",
  "crypsis",
  "pheromone",
  "trail pheromone",
  "alarm pheromone",
  "waggle dance",
  "trophallaxis",
  "parasitism",
  "hyperparasitism",
  "kleptoparasitism",
  "predation",
  "herbivory",
  "detritivory",
  "coprophagy",
  "necrophagy",
  "phytophagy",
  "frass",
  "honeydew",
  "silk",
  "gall",
  "leaf mine",
  "colony",
  "superorganism",
  "caste",
  "queen",
  "worker",
  "soldier",
  "drone",
  "alate",
  "gyne",
  "ergatoid",
  "bivouac",
  "stridulation",
  "thanatosis",
  "nuptial flight",
  "lek",
  "courtship",
  "oviposition",
  "parthenogenesis",
  "haplodiploidy",
  "altruism",
  "kin selection",
  "inclusive fitness",
  "inquilinism",
  "myrmecophily",
  "symphily",
  "Batesian mimicry",
  "Müllerian mimicry",
  "warning coloration",
  "autotomy",
  "recruitment",
  "brood parasitism",
  "Drosophila",
  "Apis",
  "Bombus",
  "Vespa",
  "Formica",
  "Camponotus",
  "Solenopsis",
  "Atta",
  "Danaus",
  "Papilio",
  "Morpho",
  "Heliconius",
  "Manduca",
  "Bombyx",
  "Lucilia",
  "Anopheles",
  "Aedes",
  "Culex",
  "Coccinella",
  "Photinus",
  "Photuris",
  "Dynastes",
  "Goliathus",
  "Titanus",
  "Megasoma",
  "Cicindela",
  "Carabus",
  "Chrysomela",
  "Agrion",
  "Calopteryx",
  "holotype",
  "paratype",
  "syntype",
  "allotype",
  "voucher specimen",
  "pinned",
  "spread wings",
  "point mount",
  "carded",
  "relaxed",
  "Malaise trap",
  "pitfall trap",
  "sweep net",
  "aspirator",
  "pooter",
  "blacklight",
  "UV light",
  "rearing",
  "ethanol",
  "Berlese funnel",
  "beating tray",
  "window trap",
  "sticky trap",
  "light trap",
  "aquatic net",
  "kick sampling",
  "Winkler extractor",
  "Tullgren funnel",
  "transect",
  "mark recapture",
  "DNA barcoding",
  "morphological",
  "taxonomic",
  "phylogenetic",
  "cladistic",
  "molecular",
  "biogeographic",
  "iNaturalist",
  "BugGuide",
  "citizen science",
  "parataxonomy",
  "canopy",
  "understory",
  "leaf litter",
  "bark",
  "deadwood",
  "rotting wood",
  "carrion",
  "dung",
  "sap",
  "nectar",
  "pollen",
  "phloem",
  "xylem",
  "riffle",
  "bog",
  "marsh",
  "meadow",
  "prairie",
  "savanna",
  "rainforest",
  "alpine",
  "cave",
  "hypogean",
  "intertidal",
  "rhizosphere",
  "iridescence",
  "diaphanous",
  "gossamer",
  "ephemeral",
  "luminescent",
  "bioluminescent",
  "prismatic",
  "structural color",
  "melanin",
  "carotenoid",
  "ommochrome",
  "chitin",
  "cuticle",
  "hemolymph",
  "trachea",
  "resilin",
  "sclerotin",
  "megadiversity",
  "cryptic species",
  "sibling species",
  "convergent evolution",
  "endemism",
  "rarity",
  "exoskeleton",
  "sclerite",
  "apodeme",
  "hemocoel",
  "fat body",
  "malpighian tubule",
  "midgut",
  "foregut",
  "hindgut",
  "salivary gland",
  "silk gland",
  "venom gland",
  "wax gland",
  "poison gland",
  "ommatidium",
  "rhabdom",
  "photoreceptor",
  "mechanoreceptor",
  "chemoreceptor",
  "olfaction",
  "gustation",
  "thermoreception",
  "hygroreception",
  "proprioception",
  "ultraviolet vision",
  "polarized light",
  "Johnston's organ",
  "hexapod",
  "hexapoda",
  "insecta",
  "pterygota",
  "neoptera",
  "polyneoptera",
  "paraneoptera",
  "holometabola",
  "endopterygota",
  "exopterygota",
  "apterygota",
  "palaeoptera",
  "entognatha",
  "ectognatha",
  "winged",
  "flight",
  "hovering",
  "gliding",
  "thermoregulation",
  "miniaturization",
  "Nearctic",
  "Palearctic",
  "Neotropical",
  "Afrotropical",
  "Indo-Malayan",
  "Australasian",
  "Gondwanan",
  "hive",
  "nest",
  "mound",
  "burrow",
  "tunnel",
  "gallery",
  "frass tunnel",
  "web",
  "trap",
  "pupal cell",
  "brood cell",
  "propolis",
  "royal jelly",
  "beeswax",
  "casein",
  "pheromonal",
  "midge",
  "gnat",
  "cranefly",
  "horsefly",
  "hoverfly",
  "robber fly",
  "bee fly",
  "blowfly",
  "leafminer",
  "gall midge",
  "painted lady",
  "cabbage white",
  "purple emperor",
  "clouded yellow",
  "luna moth",
  "atlas moth",
  "hummingbird moth",
  "antlion larva",
  "lacewing egg",
  "scale insect",
  "mealybug",
  "treehopper",
  "spittlebug",
  "froghoppper",
  "water strider",
  "backswimmer",
  "water boatman",
  "giant water bug",
  "assassin bug",
  "shield bug",
  "stink bug",
  "lace bug",
  "bed bug",
  "Gryllus",
  "Acheta",
  "Locusta",
  "Schistocerca",
  "Periplaneta",
  "Tenodera",
  "Carausius",
  "Forficula",
  "Ephemera",
  "Perla",
  "Limnephilus",
  "Panorpa",
  "Pulex",
  "Frankliniella",
  "Sialis",
  "tracheole",
]
