[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/photos/*"
  to = "/.netlify/functions/photos/:splat"
  status = 200

[[redirects]]
  from = "/text/*"
  to = "/.netlify/functions/text/:splat"
  status = 200